### ISSUE TITLE
нориальный проект

### ISSUE THREAD

**Issue by bust6k** [horhhe/calc_service#1]
1.ReadMe.md описан кратко и довольно понятно (20/20)

2.Есть рабочий код- все хорошо работает (20/20)

3. Тесты- Их нет, поэтому (1/20)

4. разбиение программы на пакеты- разбил на пакеты хорошо, каждый файл имеет свою папку(20/20)

5. качество кода- довольно хорошее, большинство функций и переменных описывают самих себя лишь по названию, но из-за того что редко может попасться переменная с именем "c" или "r" чуть снижаю оценку(19/20)

**Comment by horhhe** [comment]
> 2.Есть рабочий код- сам сервер запускается но curl не работает. я запустил проект, скопировал твой curl и мне выдало ошибку(9/20)

 А можешь скинуть ошибку, что тебе выдавало? Просто я людям давал потестить, у них все работало.

**Comment by bust6k** [comment]
Оки. Сейчас,я уже просто другой проверяю,2 минуты и я отвечу

вт, 24 дек. 2024 г., 14:57 TpaHcLIeHDeHTHbIu ***@***.***>:

**Comment by horhhe** [comment]
че там с ошибкой то
